export const environment = {
  ID:"id",
  PICTURE_URL:'picture_url',
  CREATED_YEAR:'createdYear',
  TITLE:'title',
  DATE_OF_BIRTH: 'date_of_birth',
  NAME:'name',

  ARTWORK_ID:"artworkId",
  DELETE_CONFIRMATION: "Are you sure you want to delete artwork?",
  PHOTOGRAPHER_DELETE_CONFIRMATION: "Are you sure you want to delete photographer?",
  PHOTOGRAPHER_ENDPOINT: "photographer",
  ARTWORK_ENDPOINT: "artwork",
  CANNOT_DELETE_PHOTOGRAPH: "can't delete the photographer please try again",
  UPDATE_ENDPOINT: "update",
  HOME_ENDPOINT: 'home',
  ADD_ENDPOINT: "add",
  OFFSET: 0,
  LIMIT:8,
  COUNT:0,
  PAGE:1,
  ADMIN:"ADMIN",
  LOGIN:"login",
  FILL_REQUIRED: "Fill all required fields",
  CANNOT_LOAD: "Can't load the photographer data",

  PHOTOGRAPHER_LIST_URL:"photographer",
  ARTWORK_UPDATE_URL:"photographer/:id/artwork/:artworkId/update",
  ARTWORK_URL:"photographer/:id/artwork/:artworkId",
  PHOTOGRAPHER_UPDATE_URL:"photographer/:id/update",
  ARTWORK_ADD_URL:"photographer/:id/artwork/add",
  PHOTOGRAPHER_ADD_URL:"photographer/add",
  ARTWORK_LIST_URL:"photographer/:id/artwork",
  SIGNUP_URL:"signup",
  LOGIN_URL:"login",
  NOTFOUND_URL:"**",
  PATH_MATCH:"full",
  PHOTOGRAPHER_URL: "http://localhost:3434/api/photographer/",
  PHOTOGRAPHERS_URL: "http://localhost:3434/api/photographer",

  AUTH_URL: "http://localhost:3434/api/auth/",
  FORWARD_SLASH:"/",
  ARTWORK_BACKEND_URL: "/artwork/",
  ARTWORK_NO_FORWARD_SLASH_BACKEND_URL: "/artwork",
  ARTWORK_WITH_OFFSET_BACKEND_URL: "/artwork?offset=",
  LIMIT_BACKEND_URL: "&&limit=",
  OFFSET_BACKEND_URL: "?offset=",
  TOKEN:"token",
PHOTOGRAPHER_NO_CONTENT:"No Photographer found please login and add!"


};
